name: Taser
version: '1.0-SNAPSHOT'
main: me.mrl.taser.Taser
api-version: '1.21'
commands:
  taser:
    description: "Ottieni il taser"
    usage: "/taser [give] [taser/ricaricataser/ostia]"
    permission: "taser.get"
    permission-message: "Non hai il permesso di usare questo comando!"
    aliases:
      - "tasers"

